export default function PrivacyPolicy() {
    return (
        <div className="min-h-screen bg-white py-24 px-6">
            <div className="max-w-4xl mx-auto">
                <div className="prose prose-slate lg:prose-lg max-w-none">
                    <div className="mb-12 border-b border-slate-100 pb-8 text-center lg:text-left">
                        <h1 className="text-4xl md:text-5xl font-extrabold outfit text-[#002a3a] mb-4">Privacy Policy</h1>
                        <p className="text-gray-500 font-medium">Last updated: December 18, 2025</p>
                    </div>

                    <div className="space-y-8 text-slate-700 leading-relaxed font-outfit">
                        <section>
                            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                            <p className="mt-4">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
                        </section>

                        <section className="bg-slate-50 p-8 rounded-3xl border border-slate-100">
                            <h2 className="text-2xl font-bold text-[#002a3a] mb-4 outfit">Interpretation and Definitions</h2>
                            <div className="space-y-6">
                                <div>
                                    <h3 className="text-xl font-semibold text-[#002a3a] mb-2 outfit">Interpretation</h3>
                                    <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                                </div>
                                <div>
                                    <h3 className="text-xl font-semibold text-[#002a3a] mb-2 outfit">Definitions</h3>
                                    <p className="mb-4">For the purposes of this Privacy Policy:</p>
                                    <ul className="space-y-4 list-disc pl-6">
                                        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                                        <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                                        <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Hotel Biva and Biva FoodCourts, Hailakandi Road, Rangirkhari, Silchar, 788005.</li>
                                        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                                        <li><strong>Country</strong> refers to: Assam, India</li>
                                        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
                                        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                                        <li><strong>Service</strong> refers to the Website.</li>
                                        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                                        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                                        <li><strong>Website</strong> refers to The Biva, accessible from <a href="https://www.thebiva.com" className="text-orange-500 hover:underline" target="_blank">https://www.thebiva.com</a></li>
                                        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                                    </ul>
                                </div>
                            </div>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-[#002a3a] mb-4 outfit">Collecting and Using Your Personal Data</h2>
                            <h3 className="text-xl font-semibold text-[#002a3a] mb-3 outfit">Types of Data Collected</h3>

                            <div className="space-y-6 mt-4">
                                <div>
                                    <h4 className="font-bold text-[#002a3a] mb-2 underline underline-offset-4 decoration-orange-400">Personal Data</h4>
                                    <p className="mb-3">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                                    <ul className="list-disc pl-6 space-y-1">
                                        <li>Email address</li>
                                        <li>First name and last name</li>
                                        <li>Phone number</li>
                                        <li>Address, State, Province, ZIP/Postal code, City</li>
                                        <li>Usage Data</li>
                                    </ul>
                                </div>

                                <div>
                                    <h4 className="font-bold text-[#002a3a] mb-2 underline underline-offset-4 decoration-orange-400">Usage Data</h4>
                                    <p>Usage Data is collected automatically when using the Service.</p>
                                    <p className="mt-2">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                                </div>

                                <div>
                                    <h4 className="font-bold text-[#002a3a] mb-2 underline underline-offset-4 decoration-orange-400">Tracking Technologies and Cookies</h4>
                                    <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information.</p>
                                    <ul className="list-disc pl-6 space-y-4 mt-4">
                                        <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
                                        <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages or opened an email.</li>
                                    </ul>
                                </div>
                            </div>
                        </section>

                        <section className="bg-orange-50/30 p-8 rounded-3xl border border-orange-100">
                            <h2 className="text-2xl font-bold text-[#002a3a] mb-4 outfit">Use of Your Personal Data</h2>
                            <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
                            <ul className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <li className="bg-white p-4 rounded-xl border border-slate-100"><strong>Service Maintenance:</strong> To provide and maintain our Service, including monitoring usage.</li>
                                <li className="bg-white p-4 rounded-xl border border-slate-100"><strong>Account Management:</strong> To manage Your registration as a user of the Service.</li>
                                <li className="bg-white p-4 rounded-xl border border-slate-100"><strong>Contract Performance:</strong> For the development and undertaking of purchase contracts.</li>
                                <li className="bg-white p-4 rounded-xl border border-slate-100"><strong>Communication:</strong> To contact You by email, phone, SMS regarding updates.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-[#002a3a] mb-4 outfit">Security of Your Personal Data</h2>
                            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                        </section>

                        <section className="pt-12 border-t border-slate-100 text-center">
                            <h2 className="text-2xl font-bold text-[#002a3a] mb-4 outfit">Contact Us</h2>
                            <p className="mb-6 text-gray-600">If you have any questions about this Privacy Policy, You can contact us:</p>
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                                <div className="p-4 bg-slate-50 rounded-2xl">
                                    <p className="font-bold text-sm text-orange-500 uppercase tracking-wider mb-1">Email</p>
                                    <p className="text-xs font-semibold">hello@thebiva.com</p>
                                </div>
                                <div className="p-4 bg-slate-50 rounded-2xl">
                                    <p className="font-bold text-sm text-orange-500 uppercase tracking-wider mb-1">Website</p>
                                    <p className="text-xs font-semibold">www.thebiva.com</p>
                                </div>
                                <div className="p-4 bg-slate-50 rounded-2xl">
                                    <p className="font-bold text-sm text-orange-500 uppercase tracking-wider mb-1">Phone</p>
                                    <p className="text-xs font-semibold">+91 81359 38393</p>
                                </div>
                                <div className="p-4 bg-slate-50 rounded-2xl">
                                    <p className="font-bold text-sm text-orange-500 uppercase tracking-wider mb-1">Mail</p>
                                    <p className="text-[10px] font-semibold">Hailakandi Road, Silchar, Assam, 788005</p>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    );
}
